# Form implementation generated from reading ui file 'schedule.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 675)
        MainWindow.setStyleSheet("#frame_monday, #frame_tuesday, #frame_wednesday, #frame_thursday, #frame_friday, #frame_saturday, #frame_sunday {\n"
                                 "    border: 1px solid #f0f0f0;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollArea{\n"
                                 "    background-color: #ffffff;\n"
                                 "}\n"
                                 "\n"
                                 "#header_sunday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_sunday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_monday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_monday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_tuesday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_tuesday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_wednesday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_wednesday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_thursday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_thursday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_friday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_friday{\n"
                                 "    color: white;\n"
                                 "}\n"
                                 "\n"
                                 "#header_saturday{\n"
                                 "    background-color: #00a896;\n"
                                 "}\n"
                                 "\n"
                                 "#title_saturday{\n"
                                 "    color: white;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_date = QtWidgets.QLabel(self.header)
        self.label_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.verticalLayout_18.addWidget(self.label_date)
        self.verticalLayout.addWidget(self.header)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_sunday = QtWidgets.QFrame(self.content)
        self.frame_sunday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_sunday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_sunday.setObjectName("frame_sunday")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_sunday)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_sunday = QtWidgets.QWidget(self.frame_sunday)
        self.header_sunday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_sunday.setObjectName("header_sunday")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.header_sunday)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_sunday = QtWidgets.QLabel(self.header_sunday)
        self.title_sunday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_sunday.setObjectName("title_sunday")
        self.verticalLayout_3.addWidget(self.title_sunday)
        self.verticalLayout_2.addWidget(self.header_sunday)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_sunday)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 114, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.evento = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evento.sizePolicy().hasHeightForWidth())
        self.evento.setSizePolicy(sizePolicy)
        self.evento.setStyleSheet("#evento{\n"
                                  "    border-bottom: 1px solid #f0f0f0;\n"
                                  "}")
        self.evento.setObjectName("evento")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.evento)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(self.evento)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.evento)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.verticalLayout_17.addWidget(self.evento)

        self.spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(self.spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.frame_sunday)
        self.frame_monday = QtWidgets.QFrame(self.content)
        self.frame_monday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_monday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_monday.setObjectName("frame_monday")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_monday)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_monday = QtWidgets.QWidget(self.frame_monday)
        self.header_monday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_monday.setObjectName("header_monday")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.header_monday)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_monday = QtWidgets.QLabel(self.header_monday)
        self.title_monday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_monday.setObjectName("title_monday")
        self.verticalLayout_4.addWidget(self.title_monday)
        self.verticalLayout_5.addWidget(self.header_monday)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_monday)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 103, 599))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_19.addItem(self.spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.frame_monday)
        self.frame_tuesday = QtWidgets.QFrame(self.content)
        self.frame_tuesday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tuesday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tuesday.setObjectName("frame_tuesday")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_tuesday)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.header_tuesday = QtWidgets.QWidget(self.frame_tuesday)
        self.header_tuesday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_tuesday.setObjectName("header_tuesday")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.header_tuesday)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_tuesday = QtWidgets.QLabel(self.header_tuesday)
        self.title_tuesday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_tuesday.setObjectName("title_tuesday")
        self.verticalLayout_6.addWidget(self.title_tuesday)
        self.verticalLayout_7.addWidget(self.header_tuesday)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_tuesday)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 104, 599))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_20.addItem(self.spacerItem2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.horizontalLayout.addWidget(self.frame_tuesday)
        self.frame_wednesday = QtWidgets.QFrame(self.content)
        self.frame_wednesday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_wednesday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_wednesday.setObjectName("frame_wednesday")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_wednesday)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.header_wednesday = QtWidgets.QWidget(self.frame_wednesday)
        self.header_wednesday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_wednesday.setObjectName("header_wednesday")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.header_wednesday)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.title_wednesday = QtWidgets.QLabel(self.header_wednesday)
        self.title_wednesday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_wednesday.setObjectName("title_wednesday")
        self.verticalLayout_8.addWidget(self.title_wednesday)
        self.verticalLayout_9.addWidget(self.header_wednesday)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_wednesday)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 103, 599))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_21.addItem(self.spacerItem3)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_9.addWidget(self.scrollArea_4)
        self.horizontalLayout.addWidget(self.frame_wednesday)
        self.frame_thursday = QtWidgets.QFrame(self.content)
        self.frame_thursday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_thursday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_thursday.setObjectName("frame_thursday")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_thursday)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.header_thursday = QtWidgets.QWidget(self.frame_thursday)
        self.header_thursday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_thursday.setObjectName("header_thursday")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.header_thursday)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.title_thursday = QtWidgets.QLabel(self.header_thursday)
        self.title_thursday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_thursday.setObjectName("title_thursday")
        self.verticalLayout_10.addWidget(self.title_thursday)
        self.verticalLayout_11.addWidget(self.header_thursday)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_thursday)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 103, 599))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_22.addItem(self.spacerItem4)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_11.addWidget(self.scrollArea_5)
        self.horizontalLayout.addWidget(self.frame_thursday)
        self.frame_friday = QtWidgets.QFrame(self.content)
        self.frame_friday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_friday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_friday.setObjectName("frame_friday")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_friday)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.header_friday = QtWidgets.QWidget(self.frame_friday)
        self.header_friday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_friday.setObjectName("header_friday")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.header_friday)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.title_friday = QtWidgets.QLabel(self.header_friday)
        self.title_friday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_friday.setObjectName("title_friday")
        self.verticalLayout_12.addWidget(self.title_friday)
        self.verticalLayout_13.addWidget(self.header_friday)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.frame_friday)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 104, 599))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_23.addItem(self.spacerItem5)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_13.addWidget(self.scrollArea_6)
        self.horizontalLayout.addWidget(self.frame_friday)
        self.frame_saturday = QtWidgets.QFrame(self.content)
        self.frame_saturday.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_saturday.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_saturday.setObjectName("frame_saturday")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_saturday)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.header_saturday = QtWidgets.QWidget(self.frame_saturday)
        self.header_saturday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_saturday.setObjectName("header_saturday")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.header_saturday)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.title_saturday = QtWidgets.QLabel(self.header_saturday)
        self.title_saturday.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_saturday.setObjectName("title_saturday")
        self.verticalLayout_14.addWidget(self.title_saturday)
        self.verticalLayout_15.addWidget(self.header_saturday)
        self.scrollArea_7 = QtWidgets.QScrollArea(self.frame_saturday)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 103, 599))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_24.addItem(self.spacerItem6)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_15.addWidget(self.scrollArea_7)
        self.horizontalLayout.addWidget(self.frame_saturday)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.myCode()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def myCode(self):
        class EventWidget(QtWidgets.QWidget):
            def __init__(self, parent, text='None', hour='00:00', id=-1):
                super().__init__(parent)
                self.id = id
                self.text = text
                self.hour = hour
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                                   QtWidgets.QSizePolicy.Policy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
                self.setSizePolicy(sizePolicy)
                self.setStyleSheet("QWidget{\n"
                                   "    border-bottom: 1px solid #f0f0f0;\n"
                                   "}")

                self.verticalLayout_16 = QtWidgets.QVBoxLayout(self)
                self.verticalLayout_16.setObjectName("verticalLayout_16")
                self.label_2 = QtWidgets.QLabel(self)
                self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_16.addWidget(self.label_2)
                self.label = QtWidgets.QLabel(self)
                self.label.setWordWrap(True)
                self.label.setObjectName("label")
                self.verticalLayout_16.addWidget(self.label)
                self.label_2.setText(hour)
                self.label.setText(text)
        self.frames = [
            {"scrollArea": self.scrollAreaWidgetContents, "layout": self.verticalLayout_17, "spacer": self.spacerItem},
            {"scrollArea": self.scrollAreaWidgetContents_2, "layout": self.verticalLayout_19, "spacer": self.spacerItem1},
            {"scrollArea": self.scrollAreaWidgetContents_3, "layout": self.verticalLayout_20, "spacer": self.spacerItem2},
            {"scrollArea": self.scrollAreaWidgetContents_4, "layout": self.verticalLayout_21, "spacer": self.spacerItem3},
            {"scrollArea": self.scrollAreaWidgetContents_5, "layout": self.verticalLayout_22, "spacer": self.spacerItem4},
            {"scrollArea": self.scrollAreaWidgetContents_6, "layout": self.verticalLayout_23, "spacer": self.spacerItem5},
            {"scrollArea": self.scrollAreaWidgetContents_7, "layout": self.verticalLayout_24, "spacer": self.spacerItem6}
        ]
        """for i in range(0, 10):
            for k, v in enumerate(self.frames):
                self.teste = EventWidget(self.frames[k]["scrollArea"], "Oi", "Oi")
                self.frames[k]["layout"].removeItem(self.frames[k]["spacer"])
                self.frames[k]["layout"].addWidget(self.teste)
                self.frames[k]["layout"].addItem(self.frames[k]["spacer"])"""
        import moment
        self.label_date.setText(moment.now().locale('Brazil/Acre').format('YYYY-mm-DD'))
        with open('./../data/events.json', 'r+') as file:
            data = json.load(file)['events']
        self.events = [[], [], [], [], [], [], []]
        k = 0
        for event in data:
            date = moment.date(event["date"], "%m-%d-%Y")
            weekday = int(date.weekday)
            new_event = EventWidget(self.frames[weekday]["scrollArea"], event["description"], event["hour"])
            self.frames[weekday]["layout"].removeItem(self.frames[weekday]["spacer"])
            self.frames[weekday]["layout"].addWidget(new_event)
            self.frames[weekday]["layout"].addItem(self.frames[weekday]["spacer"])
            self.events[weekday].append(new_event)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_date.setText(_translate("MainWindow", "13 de janeiro de 2022"))
        self.title_sunday.setText(_translate("MainWindow", "Domingo"))
        self.label_2.setText(_translate("MainWindow", "14:30"))
        self.label.setText(_translate("MainWindow", "Atividade em casa"))
        self.title_monday.setText(_translate("MainWindow", "Segunda"))
        self.title_tuesday.setText(_translate("MainWindow", "Terça"))
        self.title_wednesday.setText(_translate("MainWindow", "Quarta"))
        self.title_thursday.setText(_translate("MainWindow", "Quinta"))
        self.title_friday.setText(_translate("MainWindow", "Sexta"))
        self.title_saturday.setText(_translate("MainWindow", "Sábado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
